package ikev2

import "fmt"

// NotifyTypeToString 将 IKEv2 Notify 消息类型转换为人类可读的描述
func NotifyTypeToString(t uint16) string {
	switch t {
	// 错误类型 (0-16383)
	case UNSUPPORTED_CRITICAL_PAYLOAD:
		return "UNSUPPORTED_CRITICAL_PAYLOAD"
	case INVALID_IKE_SPI:
		return "INVALID_IKE_SPI"
	case INVALID_MAJOR_VERSION:
		return "INVALID_MAJOR_VERSION"
	case INVALID_SYNTAX:
		return "INVALID_SYNTAX"
	case INVALID_MESSAGE_ID:
		return "INVALID_MESSAGE_ID"
	case INVALID_SPI:
		return "INVALID_SPI"
	case NO_PROPOSAL_CHOSEN:
		return "NO_PROPOSAL_CHOSEN"
	case INVALID_KE_PAYLOAD:
		return "INVALID_KE_PAYLOAD"
	case AUTHENTICATION_FAILED:
		return "AUTHENTICATION_FAILED"
	case SINGLE_PAIR_REQUIRED:
		return "SINGLE_PAIR_REQUIRED"
	case NO_ADDITIONAL_SAS:
		return "NO_ADDITIONAL_SAS"
	case INTERNAL_ADDRESS_FAILURE:
		return "INTERNAL_ADDRESS_FAILURE"
	case FAILED_CP_REQUIRED:
		return "FAILED_CP_REQUIRED"
	case TS_UNACCEPTABLE:
		return "TS_UNACCEPTABLE"
	case INVALID_SELECTORS:
		return "INVALID_SELECTORS"
	case TEMPORARY_FAILURE:
		return "TEMPORARY_FAILURE"
	case CHILD_SA_NOT_FOUND:
		return "CHILD_SA_NOT_FOUND"

	// 状态类型 (16384+)
	case INITIAL_CONTACT:
		return "INITIAL_CONTACT"
	case NAT_DETECTION_SOURCE_IP:
		return "NAT_DETECTION_SOURCE_IP"
	case NAT_DETECTION_DESTINATION_IP:
		return "NAT_DETECTION_DESTINATION_IP"
	case COOKIE:
		return "COOKIE"
	case USE_TRANSPORT_MODE:
		return "USE_TRANSPORT_MODE"
	case REKEY_SA:
		return "REKEY_SA"
	case MOBIKE_SUPPORTED:
		return "MOBIKE_SUPPORTED"
	case UPDATE_SA_ADDRESSES:
		return "UPDATE_SA_ADDRESSES"
	case AUTH_LIFETIME:
		return "AUTH_LIFETIME"
	case REDIRECT_SUPPORTED:
		return "REDIRECT_SUPPORTED"
	case REDIRECT:
		return "REDIRECT"
	case TICKET_LT_OPAQUE:
		return "TICKET_LT_OPAQUE"
	case TICKET_REQUEST:
		return "TICKET_REQUEST"
	case EAP_ONLY_AUTHENTICATION:
		return "EAP_ONLY_AUTHENTICATION"
	case IKEV2_FRAGMENTATION_SUPPORTED:
		return "IKEV2_FRAGMENTATION_SUPPORTED"
	case DEVICE_IDENTITY:
		return "DEVICE_IDENTITY"
	case DEVICE_IDENTITY_3GPP:
		return "DEVICE_IDENTITY_3GPP"

	// 3GPP 私有 Notify Types (TS 24.302)
	case 8192:
		return "3GPP_BACKOFF_TIMER" // 退避定时器
	case 41041:
		return "3GPP_EMERGENCY_SUPPORT"
	}

	if t < 16384 {
		return fmt.Sprintf("UNKNOWN_ERROR(%d)", t)
	}
	return fmt.Sprintf("UNKNOWN_STATUS(%d)", t)
}
